[package]
name = "m3u8"
version = "0.1.0"
edition = "2024"

[dependencies]
fast-float2 = "0.2"
memchr = "2.7"

[dev-dependencies]
criterion = "0.6"
pretty_assertions = "1.4.1"
paste = "1.0"
hls_m3u8 = "0.5.1"
m3u8-rs = "6.0.0"

[[bench]]
name = "line_parse_bench"
harness = false
